import { useState, useEffect, useRef } from 'react';
import { Dialog, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { QRDisplay } from '@/components/identity/QRDisplay';
import { QRScanner } from '@/components/p2p/QRScanner';
import { useConnectionsStore } from '@/stores/connections.store';
import { useSyncStore } from '@/stores/sync.store';
import { Copy, Check, Loader2, Wifi } from 'lucide-react';
import { estimateBlobSize, isSignalingBlob } from '@/lib/p2p/signaling-codec';
import { P2PDebugPanel } from '@/components/p2p/P2PDebugPanel';

interface ConnectPeerDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  groupId: string;
}

type Step = 'creating' | 'show-offer' | 'scan-answer' | 'waiting-ice' | 'connected' | 'error';

export function ConnectPeerDialog({ open, onOpenChange, groupId }: ConnectPeerDialogProps) {
  const [step, setStep] = useState<Step>('creating');
  const [copied, setCopied] = useState(false);
  const [localError, setLocalError] = useState<string | null>(null);
  const { offerBlob, isCreatingOffer, error, connectingPeerId, createOffer, completeConnection, reset } = useConnectionsStore();
  const connectingStatus = useSyncStore(s => connectingPeerId ? s.peers[connectingPeerId]?.status : undefined);
  const iceTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const displayError = localError || error;

  // wait for peer:connect from the exact peer whose answer we scanned; keep
  // watching after the timeout since the handshake may still finish
  useEffect(() => {
    if (step !== 'waiting-ice' && step !== 'error') return;
    if (connectingStatus === 'synced' || connectingStatus === 'syncing') {
      if (iceTimeoutRef.current) clearTimeout(iceTimeoutRef.current);
      setLocalError(null);
      setStep('connected');
      setTimeout(() => onOpenChange(false), 2000);
    }
  }, [connectingStatus, step]);

  const startOffer = (gid: string) => {
    reset();
    setStep('creating');
    setLocalError(null);
    createOffer(gid).then(() => {
      const state = useConnectionsStore.getState();
      if (state.error) {
        setStep('error');
      } else if (state.offerBlob) {
        setStep('show-offer');
      } else {
        setLocalError('ICE gathering timed out: no network candidates found. Check your internet connection.');
        setStep('error');
      }
    }).catch(err => {
      setLocalError(`Failed to create offer: ${err instanceof Error ? err.message : String(err)}`);
      setStep('error');
    });
  };

  useEffect(() => {
    if (open) {
      startOffer(groupId);
    }
  }, [open]);

  const handleClose = () => {
    if (iceTimeoutRef.current) clearTimeout(iceTimeoutRef.current);
    reset();
    setStep('creating');
    setLocalError(null);
    onOpenChange(false);
  };

  const handleCopy = async () => {
    if (!offerBlob) return;
    await navigator.clipboard.writeText(offerBlob);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleAnswerReceived = async (answerBlob: string) => {
    setLocalError(null);
    try {
      if (!isSignalingBlob(answerBlob)) {
        setLocalError('Invalid QR code. Scan the FS2: or FS3: response code generated by your friend for this connection.');
        setStep('error');
        return;
      }
      // Wait for the peer-connect event; accepting the answer only starts negotiation.
      await completeConnection(answerBlob);
      if (useConnectionsStore.getState().error) {
        setStep('error');
        return;
      }
      setStep('waiting-ice');
      iceTimeoutRef.current = setTimeout(() => {
        setLocalError('Connection timed out while establishing a direct link. Try again, or make sure both devices have a working internet connection.');
        setStep('error');
      }, 20000);
    } catch (err) {
      setLocalError(`Failed to complete connection: ${err instanceof Error ? err.message : String(err)}`);
      setStep('error');
    }
  };

  const blobInfo = offerBlob ? estimateBlobSize(offerBlob) : null;

  return (
    <Dialog open={open} onOpenChange={(isOpen) => { if (!isOpen) handleClose(); }}>
      <DialogHeader>
        <DialogTitle>Connect to Peer</DialogTitle>
        <DialogDescription aria-live="polite">
          {step === 'creating' && 'Preparing connection...'}
          {step === 'show-offer' && 'Show this code to your friend, then scan their response.'}
          {step === 'scan-answer' && 'Scan your friend\'s response code.'}
          {step === 'waiting-ice' && 'Establishing secure connection...'}
          {step === 'connected' && 'Connected!'}
          {step === 'error' && 'Connection failed.'}
        </DialogDescription>
      </DialogHeader>

      <div className="space-y-4">
        {(step === 'creating' || isCreatingOffer) && (
          <div className="flex flex-col items-center py-8">
            <Loader2 className="h-8 w-8 animate-spin text-primary" />
            <p className="text-sm text-muted-foreground mt-3">Gathering network info... (can take up to 20s on some devices)</p>
          </div>
        )}

        {step === 'show-offer' && offerBlob && (
          <div className="space-y-3">
            <p className="text-xs font-medium text-muted-foreground">Step 1: Show this to your friend</p>

            {blobInfo?.fitsQR && (
              <div className="flex justify-center p-3 bg-white rounded-lg">
                <QRDisplay data={offerBlob} size={220} />
              </div>
            )}

            <div className="flex gap-2">
              <Input
                value={offerBlob}
                readOnly
                className="text-xs font-mono"
                onClick={e => (e.target as HTMLInputElement).select()}
              />
              <Button variant="outline" size="icon" onClick={handleCopy}>
                {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
              </Button>
            </div>

            {blobInfo && (
              <p className="text-xs text-muted-foreground text-center">
                {blobInfo.bytes} bytes {blobInfo.fitsQR ? '(QR-compatible)' : '(too large for QR, use copy/paste)'}
              </p>
            )}

            <Button className="w-full" onClick={() => setStep('scan-answer')}>
              I've shared it: scan their response
            </Button>
          </div>
        )}

        {step === 'scan-answer' && (
          <div className="space-y-3">
            <p className="text-xs font-medium text-muted-foreground">Step 2: Scan your friend's response code</p>
            <QRScanner
              onScan={handleAnswerReceived}
              onError={(msg) => { setLocalError(msg); setStep('error'); }}
            />
          </div>
        )}

        {step === 'waiting-ice' && (
          <div className="flex flex-col items-center py-8 gap-3">
            <Loader2 className="h-8 w-8 animate-spin text-primary" />
            <p className="text-sm font-medium">Establishing connection...</p>
            <p className="text-xs text-muted-foreground text-center">
              Negotiating a direct link between devices.<br />This may take up to 30 seconds.
            </p>
            <P2PDebugPanel />
          </div>
        )}

        {step === 'connected' && (
          <div className="flex flex-col items-center py-8">
            <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center">
              <Wifi className="h-8 w-8 text-green-600" />
            </div>
            <p className="text-sm font-medium mt-3 text-green-600">Connected! Syncing data...</p>
          </div>
        )}

        {(step === 'error' || (error && step !== 'creating')) && (
          <div className="text-center py-4 space-y-3">
            <div className="w-12 h-12 bg-destructive/10 rounded-full flex items-center justify-center mx-auto">
              <span className="text-destructive text-xl">✕</span>
            </div>
            <p className="text-sm font-medium text-destructive">Connection Failed</p>
            {displayError && (
              <p className="text-xs text-muted-foreground bg-muted rounded p-2 text-left font-mono break-all">
                {displayError}
              </p>
            )}
            <P2PDebugPanel />
            <Button variant="outline" className="w-full" onClick={() => startOffer(groupId)}>
              Try Again
            </Button>
          </div>
        )}
      </div>
    </Dialog>
  );
}
