import { useState } from 'react';
import { Dialog, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { QRDisplay } from '@/components/identity/QRDisplay';
import { QRScanner } from '@/components/p2p/QRScanner';
import { useConnectionsStore } from '@/stores/connections.store';
import { Copy, Check, Loader2, Wifi } from 'lucide-react';
import { estimateBlobSize, isSignalingBlob } from '@/lib/p2p/signaling-codec';

interface JoinPeerDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

type Step = 'scan-offer' | 'generating' | 'show-answer' | 'connected' | 'error';

export function JoinPeerDialog({ open, onOpenChange }: JoinPeerDialogProps) {
  const [step, setStep] = useState<Step>('scan-offer');
  const [copied, setCopied] = useState(false);
  const [localError, setLocalError] = useState<string | null>(null);
  const { answerBlob, isAcceptingOffer, error, acceptOffer, reset } = useConnectionsStore();

  const handleOpen = (isOpen: boolean) => {
    if (!isOpen) {
      reset();
      setLocalError(null);
      setStep('scan-offer');
    }
    onOpenChange(isOpen);
  };

  const handleOfferReceived = async (offerBlob: string) => {
    if (!isSignalingBlob(offerBlob)) {
      reset();
      setLocalError('Invalid QR code. Scan the FS2: or FS3: connection code generated by the group creator.');
      setStep('error');
      return;
    }
    setLocalError(null);
    setStep('generating');
    await acceptOffer(offerBlob);
    if (useConnectionsStore.getState().error) {
      setStep('error');
    } else {
      setStep('show-answer');
    }
  };

  const handleCopy = async () => {
    if (!answerBlob) return;
    await navigator.clipboard.writeText(answerBlob);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const blobInfo = answerBlob ? estimateBlobSize(answerBlob) : null;

  return (
    <Dialog open={open} onOpenChange={handleOpen}>
      <DialogHeader>
        <DialogTitle>Join Peer</DialogTitle>
        <DialogDescription aria-live="polite">
          {step === 'scan-offer' && 'Scan your friend\'s connection code.'}
          {step === 'generating' && 'Preparing your response...'}
          {step === 'show-answer' && 'Show this response code to your friend to complete the connection.'}
          {step === 'connected' && 'Connected!'}
          {step === 'error' && 'Connection failed.'}
        </DialogDescription>
      </DialogHeader>

      <div className="space-y-4">
        {step === 'scan-offer' && (
          <div className="space-y-3">
            <p className="text-xs font-medium text-muted-foreground">Step 1: Scan your friend's code</p>
            <QRScanner onScan={handleOfferReceived} />
          </div>
        )}

        {(step === 'generating' || isAcceptingOffer) && (
          <div className="flex flex-col items-center py-8">
            <Loader2 className="h-8 w-8 animate-spin text-primary" />
            <p className="text-sm text-muted-foreground mt-3">Generating response (~3s)...</p>
          </div>
        )}

        {step === 'show-answer' && answerBlob && (
          <div className="space-y-3">
            <p className="text-xs font-medium text-muted-foreground">Step 2: Show this response to your friend</p>

            {blobInfo?.fitsQR && (
              <div className="flex justify-center p-3 bg-white rounded-lg">
                <QRDisplay data={answerBlob} size={220} />
              </div>
            )}

            <div className="flex gap-2">
              <Input
                value={answerBlob}
                readOnly
                className="text-xs font-mono"
                onClick={e => (e.target as HTMLInputElement).select()}
              />
              <Button variant="outline" size="icon" onClick={handleCopy}>
                {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
              </Button>
            </div>

            {blobInfo && (
              <p className="text-xs text-muted-foreground text-center">
                {blobInfo.bytes} bytes {blobInfo.fitsQR ? '(QR-compatible)' : '(too large for QR, use copy/paste)'}
              </p>
            )}

            <p className="text-xs text-muted-foreground text-center">
              Once your friend scans this, you'll be connected automatically.
            </p>
          </div>
        )}

        {step === 'connected' && (
          <div className="flex flex-col items-center py-8">
            <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center">
              <Wifi className="h-8 w-8 text-green-600" />
            </div>
            <p className="text-sm font-medium mt-3 text-green-600">Connected! Syncing data...</p>
          </div>
        )}

        {(step === 'error' || error) && (
          <div className="text-center py-4">
            <p className="text-sm text-destructive">{localError || error || 'Connection failed'}</p>
            <Button variant="outline" className="mt-3" onClick={() => { reset(); setLocalError(null); setStep('scan-offer'); }}>
              Try Again
            </Button>
          </div>
        )}
      </div>
    </Dialog>
  );
}
