import { useState, useEffect, useReducer, useRef } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { UserPlus, Wifi, Link } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Header } from '@/components/layout/Header';
import { QRScanner } from '@/components/p2p/QRScanner';
import { QRDisplay } from '@/components/identity/QRDisplay';
import { P2PDebugPanel } from '@/components/p2p/P2PDebugPanel';
import { estimateBlobSize, isSignalingBlob } from '@/lib/p2p/signaling-codec';
import { useGroupsStore } from '@/stores/groups.store';
import { useIdentityStore } from '@/stores/identity.store';
import { useSyncStore } from '@/stores/sync.store';
import { useConnectionsStore } from '@/stores/connections.store';
import { useShallow } from 'zustand/react/shallow';

export function JoinGroup() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const identity = useIdentityStore(s => s.identity);
  const documents = useGroupsStore(s => s.documents);
  const joinGroup = useSyncStore(s => s.joinGroup);
  const lastSendError = useSyncStore(s => s.lastSendError);
  const clearSendError = useSyncStore(s => s.clearSendError);
  const { acceptOffer, answerBlob, isAcceptingOffer, error, reset } = useConnectionsStore(useShallow(s => ({
    acceptOffer: s.acceptOffer, answerBlob: s.answerBlob, isAcceptingOffer: s.isAcceptingOffer, error: s.error, reset: s.reset,
  })));
  const [state, dispatch] = useReducer(joinReducer, initialJoinState);
  const { step, localError, pendingGroupId, copied } = state;
  const timeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const topic = searchParams.get('topic') || '';
  const groupName = searchParams.get('name') || 'Unknown Group';

  const alreadyJoined = topic && documents[topic] !== undefined;

  // Auto-navigate when group document arrives after connection.
  useEffect(() => {
    if (!pendingGroupId) return;
    const doc = documents[pendingGroupId];
    if (doc) {
      if (timeoutRef.current) clearTimeout(timeoutRef.current);
      dispatch({ type: 'GROUP_ARRIVED' });
      navigate(`/group/${pendingGroupId}`);
    }
  }, [documents, pendingGroupId]);

  // don't make the user wait out the full 30s timeout for an error we already know about
  useEffect(() => {
    if (!pendingGroupId || !lastSendError) return;
    if (timeoutRef.current) clearTimeout(timeoutRef.current);
    dispatch({ type: 'FAIL', message: lastSendError });
    clearSendError();
  }, [pendingGroupId, lastSendError]);

  // 30s connection timeout: show error if group never arrives
  const startConnectionTimeout = () => {
    timeoutRef.current = setTimeout(() => {
      dispatch({ type: 'FAIL', message: 'Connection timed out. The group data was not received. Try reconnecting.' });
    }, 30000);
  };

  // clear any pending connection timeout on unmount so state setters on a
  // stale closure don't fire after the component is gone.
  useEffect(() => () => {
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current);
      timeoutRef.current = null;
    }
  }, []);

  const displayError = localError || error;

  const handleScanOffer = async (offerBlob: string) => {
    if (!identity) return;
    dispatch({ type: 'CLEAR_ERROR' });
    try {
      if (!isSignalingBlob(offerBlob)) {
        dispatch({ type: 'FAIL', message: 'Invalid QR code. Scan the FS2: or FS3: connection code generated by the group creator.' });
        return;
      }
      const result = await acceptOffer(offerBlob);
      if (result) {
        joinGroup(result.groupId);
        dispatch({ type: 'OFFER_ACCEPTED', groupId: result.groupId });
        startConnectionTimeout();
      } else {
        dispatch({ type: 'FAIL', message: useConnectionsStore.getState().error || 'Failed to process connection offer.' });
      }
    } catch (err) {
      dispatch({ type: 'FAIL', message: `Connection failed: ${err instanceof Error ? err.message : String(err)}` });
    }
  };

  const handleRetry = () => {
    reset();
    if (timeoutRef.current) clearTimeout(timeoutRef.current);
    dispatch({ type: 'RETRY' });
  };

  const handleCopy = async () => {
    if (!answerBlob) return;
    await navigator.clipboard.writeText(answerBlob);
    dispatch({ type: 'SET_COPIED', copied: true });
    setTimeout(() => dispatch({ type: 'SET_COPIED', copied: false }), 2000);
  };

  const [manualCode, setManualCode] = useState('');

  if (!identity) {
    return (
      <div className="flex flex-col">
        <Header title="Join Group" showBack />
        <div className="p-4 flex flex-col items-center gap-3 py-16">
          <div className="w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin" />
          <p className="text-sm text-muted-foreground">Loading identity...</p>
        </div>
      </div>
    );
  }

  if (!topic) {
    // a scanned URL can only ever send us to /join, never e.g. /onboarding
    const openInviteText = (trimmed: string) => {
      try {
        const url = new URL(trimmed);
        if (url.pathname === '/join') {
          navigate(url.pathname + url.search);
          return;
        }
        dispatch({ type: 'SCAN_ERROR', message: 'That link is not a FairShare invite.' });
      } catch {
        navigate(`/join?topic=${encodeURIComponent(trimmed)}`);
      }
    };

    const handleManualJoin = () => {
      const trimmed = manualCode.trim();
      if (!trimmed) return;
      // Signaling blobs are WebRTC offers; process directly instead of navigating.
      if (isSignalingBlob(trimmed)) {
        handleScanOffer(trimmed);
        return;
      }
      openInviteText(trimmed);
    };

    const handleQRScan = (data: string) => {
      const trimmed = data.trim();
      // Signaling blobs are WebRTC offers; process directly instead of navigating.
      if (isSignalingBlob(trimmed)) {
        handleScanOffer(trimmed);
        return;
      }
      openInviteText(trimmed);
    };

    return (
      <div className="flex flex-col">
        <Header title="Join Group" showBack />
        <div className="p-4 space-y-4">
          <Card>
            <CardContent className="p-6 space-y-4">

              {/* Step-based UI after a connection offer is scanned */}
              {step === 'show-answer' && answerBlob && (
                <>
                  <div className="text-center">
                    <h2 className="text-lg font-semibold">Show this to the creator</h2>
                    <p className="text-sm text-muted-foreground mt-1">They need to scan your response to complete the connection.</p>
                  </div>
                  {estimateBlobSize(answerBlob).fitsQR && (
                    <div className="flex justify-center p-3 bg-white rounded-lg">
                      <QRDisplay data={answerBlob} size={220} />
                    </div>
                  )}
                  <div className="flex gap-2">
                    <input readOnly value={answerBlob}
                      className="flex-1 text-xs font-mono border rounded px-2 py-1 truncate"
                      onClick={e => (e.target as HTMLInputElement).select()} />
                    <Button variant="outline" size="sm" onClick={handleCopy}>{copied ? 'Copied!' : 'Copy'}</Button>
                  </div>
                  <div className="flex items-center gap-2 py-2">
                    <div className="w-5 h-5 border-2 border-primary border-t-transparent rounded-full animate-spin flex-shrink-0" />
                    <p className="text-xs text-muted-foreground">Waiting for creator to scan... Group will open automatically.</p>
                  </div>
                  <P2PDebugPanel />
                </>
              )}

              {step === 'connected' && (
                <div className="py-4 text-center">
                  <Wifi className="w-12 h-12 text-green-600 mx-auto mb-2" />
                  <p className="text-sm font-medium text-green-600">Connected! Syncing group data...</p>
                </div>
              )}

              {step === 'error' && (
                <div className="py-4 text-center space-y-3">
                  <span className="text-destructive text-2xl">✕</span>
                  <p className="text-sm font-medium text-destructive">Connection Failed</p>
                  {(localError || error) && (
                    <p className="text-xs text-muted-foreground bg-muted rounded p-2 font-mono break-all">{localError || error}</p>
                  )}
                  <P2PDebugPanel />
                  <Button variant="outline" onClick={handleRetry}>Try Again</Button>
                </div>
              )}

              {isAcceptingOffer && (
                <div className="py-4 text-center">
                  <div className="w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin mx-auto" />
                  <p className="text-sm text-muted-foreground mt-2">Processing connection offer... (can take up to 20s on some devices)</p>
                </div>
              )}

              {/* Default scan/paste UI: hide while processing. Also handles the
                  'scan' step: handleRetry() resets to 'scan' after a failed
                  connection, and this branch (no ?topic= in the URL) has no
                  separate scan-step UI, so it must fall back to this same block
                  or "Try Again" would render a blank card. */}
              {(step === 'info' || step === 'scan') && !isAcceptingOffer && (
                <>
                  <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto">
                    <Link className="w-8 h-8 text-primary" />
                  </div>
                  <div className="text-center">
                    <h2 className="text-lg font-semibold">Join a Group</h2>
                    <p className="text-sm text-muted-foreground mt-1">
                      Scan an invite QR code or paste the invite link.
                    </p>
                  </div>

                  <QRScanner
                    onScan={handleQRScan}
                    onError={(msg) => dispatch({ type: 'SCAN_ERROR', message: msg })}
                  />

                  {localError && (
                    <p className="text-xs text-destructive text-center">{localError}</p>
                  )}

                  <div className="relative flex items-center gap-2">
                    <div className="flex-1 border-t" />
                    <span className="text-xs text-muted-foreground">or paste code</span>
                    <div className="flex-1 border-t" />
                  </div>

                  <div className="flex gap-2">
                    <Input
                      placeholder="Paste invite link or topic code..."
                      value={manualCode}
                      onChange={e => setManualCode(e.target.value)}
                      onKeyDown={e => e.key === 'Enter' && handleManualJoin()}
                    />
                    <Button onClick={handleManualJoin} disabled={!manualCode.trim()}>
                      Go
                    </Button>
                  </div>
                </>
              )}

            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  if (alreadyJoined) {
    return (
      <div className="flex flex-col">
        <Header title="Join Group" showBack />
        <div className="p-4 space-y-4">
          <Card>
            <CardContent className="p-6 text-center space-y-4">
              <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto">
                <Wifi className="w-8 h-8 text-green-600" />
              </div>
              <div>
                <h2 className="text-lg font-semibold">{groupName}</h2>
                <p className="text-sm text-muted-foreground mt-1">You're already in this group.</p>
              </div>
              <Button className="w-full" onClick={() => navigate(`/group/${topic}`)}>
                Open Group
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col">
      <Header title="Join Group" showBack />

      <div className="p-4 space-y-4">
        <Card>
          <CardContent className="p-6 text-center space-y-4">
            <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto">
              <UserPlus className="w-8 h-8 text-primary" />
            </div>
            <div>
              <h2 className="text-lg font-semibold">{groupName}</h2>
              <p className="text-sm text-muted-foreground mt-1" aria-live="polite">
                {step === 'info' && "To join, scan the group creator's connection QR code."}
                {step === 'scan' && "Scan the connection QR code from the group creator."}
                {step === 'show-answer' && "Show this response to the group creator to complete the connection."}
                {step === 'connected' && "Connected! Group data is syncing..."}
              </p>
            </div>

            {step === 'info' && (
              <div className="space-y-3">
                <Button className="w-full" onClick={() => dispatch({ type: 'SET_STEP', step: 'scan' })}>
                  <UserPlus className="w-4 h-4 mr-2" />
                  Scan Creator's QR Code
                </Button>
                <p className="text-xs text-muted-foreground">
                  Ask the group creator to open the group and tap "Connect Peer". Then scan their QR code here.
                </p>
              </div>
            )}

            {step === 'scan' && (
              <div className="space-y-3">
                {isAcceptingOffer ? (
                  <div className="py-4">
                    <div className="w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin mx-auto" />
                    <p className="text-sm text-muted-foreground mt-2">Processing connection... (can take up to 20s on some devices)</p>
                  </div>
                ) : (
                  <QRScanner
                    onScan={handleScanOffer}
                    onError={(msg) => dispatch({ type: 'FAIL', message: msg })}
                  />
                )}
              </div>
            )}

            {step === 'show-answer' && (
              answerBlob ? (
                <div className="space-y-3">
                  <p className="text-xs font-medium text-muted-foreground">Step 2: Show this response to the group creator</p>
                  {estimateBlobSize(answerBlob).fitsQR && (
                    <div className="flex justify-center p-3 bg-white rounded-lg">
                      <QRDisplay data={answerBlob} size={220} />
                    </div>
                  )}
                  <div className="flex gap-2">
                    <input
                      readOnly
                      value={answerBlob}
                      className="flex-1 text-xs font-mono border rounded px-2 py-1 truncate"
                      onClick={e => (e.target as HTMLInputElement).select()}
                    />
                    <Button variant="outline" size="sm" onClick={handleCopy}>
                      {copied ? 'Copied!' : 'Copy'}
                    </Button>
                  </div>
                  <div className="flex items-center gap-2 py-2">
                    <div className="w-5 h-5 border-2 border-primary border-t-transparent rounded-full animate-spin flex-shrink-0" />
                    <p className="text-xs text-muted-foreground">Waiting for creator to scan... Group will open automatically.</p>
                  </div>
                  <P2PDebugPanel />
                </div>
              ) : (
                <div className="py-4 text-center space-y-3">
                  <p className="text-sm text-destructive">Failed to generate response code. Please try again.</p>
                  <Button variant="outline" onClick={handleRetry}>Try Again</Button>
                </div>
              )
            )}

            {step === 'connected' && (
              <div className="py-4">
                <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto">
                  <Wifi className="w-8 h-8 text-green-600" />
                </div>
                <p className="text-sm font-medium mt-3 text-green-600">Connected! Syncing group data...</p>
              </div>
            )}

            {step === 'error' && (
              <div className="py-4 text-center space-y-3">
                <div className="w-12 h-12 bg-destructive/10 rounded-full flex items-center justify-center mx-auto">
                  <span className="text-destructive text-xl">✕</span>
                </div>
                <p className="text-sm font-medium text-destructive">Connection Failed</p>
                {displayError && (
                  <p className="text-xs text-muted-foreground bg-muted rounded p-2 text-left font-mono break-all">
                    {displayError}
                  </p>
                )}
                <P2PDebugPanel />
                <div className="flex gap-2">
                  <Button variant="outline" className="flex-1" onClick={handleRetry}>Try Again</Button>
                  <Button variant="ghost" className="flex-1" onClick={() => navigate('/dashboard')}>Go Home</Button>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// Reducer state is exported for focused unit tests.

export type JoinStep = 'info' | 'scan' | 'show-answer' | 'connected' | 'error';

export interface JoinState {
  step: JoinStep;
  localError: string | null;
  pendingGroupId: string | null;
  copied: boolean;
}

export type JoinAction =
  | { type: 'SET_STEP'; step: JoinStep }
  | { type: 'OFFER_ACCEPTED'; groupId: string }
  | { type: 'FAIL'; message: string }
  | { type: 'GROUP_ARRIVED' }
  | { type: 'RETRY' }
  | { type: 'SET_COPIED'; copied: boolean }
  | { type: 'CLEAR_ERROR' }
  | { type: 'SCAN_ERROR'; message: string };

export const initialJoinState: JoinState = {
  step: 'info',
  localError: null,
  pendingGroupId: null,
  copied: false,
};

export function joinReducer(state: JoinState, action: JoinAction): JoinState {
  switch (action.type) {
    case 'SET_STEP':
      return { ...state, step: action.step };
    case 'OFFER_ACCEPTED':
      return { ...state, step: 'show-answer', pendingGroupId: action.groupId, localError: null };
    case 'FAIL':
      return { ...state, step: 'error', localError: action.message };
    case 'GROUP_ARRIVED':
      return { ...state, localError: null };
    case 'RETRY':
      return { step: 'scan', localError: null, pendingGroupId: null, copied: false };
    case 'SET_COPIED':
      return { ...state, copied: action.copied };
    case 'CLEAR_ERROR':
      return { ...state, localError: null };
    case 'SCAN_ERROR':
      return { ...state, localError: action.message };
    default:
      return state;
  }
}
